[package]
name = "auto-isa"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
either = "1.9.0"
llvm-plugin = { version = "0.4.1", features = ["llvm16-0"] }
rustix = { version = "0.38.28", features = ["runtime", "process", "stdio"] }

[dev-dependencies]
expect-test = "1.4.1"
supercilex-tests = "0.4.1"

[lib]
crate-type = ["cdylib"]
